# Generated by Django 5.0.1 on 2025-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="item",
            name="claim_status",
            field=models.CharField(
                choices=[("unclaimed", "Unclaimed"), ("claimed", "Claimed")],
                default="unclaimed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(
                default="No Location",
                help_text="Enter the Item's location manually",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("LOST", "Lost"), ("FOUND", "Found")],
                default="LOST",
                max_length=5,
            ),
        ),
    ]
