# Generated by Django 5.0.1 on 2025-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(max_length=50),  # Update this line
        ),
        migrations.AddField(
            model_name='claim',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
