# Generated by Django 5.0.1 on 2025-02-04 07:16

from django.db import migrations




def update_status_length(apps, schema_editor):
    Claim = apps.get_model("claims", "Claim")
    for claim in Claim.objects.all():
        if len(Claim.status) < 50:
            Claim.status = Claim.status[:50]
            Claim.save()


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_alter_claim_status"),
    ]

    operations = [
        migrations.RunPython(update_status_length),
    ]
