# Generated by Django 5.0.1 on 2025-02-06 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_auto_20250204_0116"),
        ("items", "0003_item_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="claim",
            name="item_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.item"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
